### ISSUE TITLE
instrustruction

### ISSUE THREAD

**Issue by wilfried18** [nixalot/aurtools#1]
it's gui or cli?
it would be nice to tell command not?

**Comment by mraspberry** [comment]
CLI. Running "python setup.py install" or makepkg (in the packaging directory) two scripts are installed. aurdownload and aursearch. aurdownload downloads packages and aursearch searches the AUR. I'll update the README soon.

**Comment by wilfried18** [comment]
Ok well thank you, I do not think I do not like using the CLI
